Feature/brick breaker 23
13-Troy/brick-breaker pull request #24
Opened 2022-04-27 19:49 UTC by KaterinaKorneeeva

возникает  ошибка при передаче children, подскажите пож как исправить

 58:9  error  Do not pass children as props. Instead, nest children between the opening and closing tags  react/no-children-prop
 Для примера в Modal передаю  children = {contentModalTest}
 const contentModalTest =  <Link to={AppRoute.ROOT}>{'Войти'}</Link>;

2022-04-28 09:59 UTC, AFL987 approved these changes

2022-04-28 09:59 UTC, AFL987 commented on src/pages/registration/Registration.tsx
> +      />
`Должно быть так <Modal
        isShown={isShown}
        hide={toggle}
        headerText="Создание поста"
      >{contentModalTest}</Modal>`

2022-04-28 20:24 UTC, gohabereg requested changes

2022-04-28 20:24 UTC, gohabereg commented on src/components/ButtonSettings/style.tsx
> +  border-bottom: 1px solid ${allColors.white};
Лучше тут брать цвет из темы

2022-04-28 20:24 UTC, gohabereg commented on src/components/Modal/Modal.tsx
> +    </>
Тут очень много фрагментов и верстка усложняется

1. Для случаев, когда компонент надо показать в зависимости от булевой переменной, можно сделать без тернарного оператора:
```
<>
  {isShown && (<>...</>)}
</>
```

2. Но тут на самом деле можно еще упростить, если вынести проверку до return:
```
if (!isShown) {
  return null;
}

return (
  <>
    <BackdropSt onClick={hide} />
    <WrapperSt>
      ...
    </WrapperSt>
  <>
);
```

2022-04-28 20:24 UTC, gohabereg commented on src/components/Modal/style.tsx
> +export const WrapperSt = styled.div`
С пустой строкой тут лучше читается
```suggestion
import styled from 'styled-components';

export const WrapperSt = styled.div`
```

Вообще можно на это дело линтер настроить

2022-04-28 20:24 UTC, gohabereg commented on src/hooks/useModal.tsx
> +};
Я бы этот хук переимновал в `useToggle`, такое поведение обычно часто нужно. Но это имхо, не обязательно менять

2022-04-28 20:24 UTC, gohabereg commented on src/components/Modal/Modal.tsx
> +    </>
А еще модальные окна обычно рендерят с помощью порталов, чтобы не было проблем с перекрытием других компонентов
https://ru.reactjs.org/docs/portals.html

Можно сейчас не менять, но в будущем стоит сделать

2022-04-29 14:55 UTC, gohabereg requested changes

2022-04-29 14:55 UTC, gohabereg commented on src/components/ButtonSettings/style.tsx
> +  color: ${allColors.white};
Вот тут остались еще цвета не из темы

2022-04-29 14:55 UTC, gohabereg commented on src/components/Modal/style.tsx
> +  background: #fff;
Можно взять из темы

2022-04-29 14:55 UTC, gohabereg commented on src/pages/profile/Profile.tsx
> +          {'Изменить данные'}
Можно не менять, но вообще для строк не обязательно добавлять {}

```suggestion
          Изменить данные
```

2022-04-29 16:53 UTC, gohabereg approved these changes

2022-04-29 16:53 UTC, gohabereg commented on src/styles/style.tsx
> +    font-family: ${baseTheme.fonts.font_family};
Тут тоже можно из темы вытащить шрифты

```suggestion
    font-family: ${({ theme }) => theme.fonts.font_family};
```

2022-04-29 17:38 UTC, merged