Feature/game mechanics
13-Troy/brick-breaker pull request #25
Opened 2022-04-28 08:07 UTC by parnasmi

2022-04-28 20:55 UTC, gohabereg requested changes
Отличная работа!

1. Кажется, что логику анимации стоит убрать внутрь объекта Game. Чтобы запуск игры выглядел в компоненте как-то так:
```
const Game = () => {
  const game = useRef();
  const canvas = useRef();

  useEffect(() => {
    game.current = new Game(canvas.current, /* можно другие параметры передать */);
  }, [])

  const onStart = () => {
    game.current?.start();
  }

  return (
    <canvas ref={canvas} ... />
  )
}
```

То есть компонент просто инициализирует игру и запускает, а вся остальная логика спрятана внутри

2. Идея с подсчетом времени — хорошая, хотя и не обязательная. Так можно сделать анимации независимыми от частоты кадров (частоты вызова animation frame)

3. Стоит подумать о том, как сделать просчет коллизий абстрактным для двух любых объектов ("стены" в таком случае тоже стоит рассматривать как объекты)

4. Рекомендую реализовать абстрактный класс `GameObject`, у которого будут стандартные методы и свойств вроде `position`, `width`, `height`, `speed`, `update` и тд

2022-04-28 20:55 UTC, gohabereg commented on public/index.html
> +<!--<img src="ball.png" id="ballImage" alt="">-->
```suggestion
```

2022-04-28 20:55 UTC, gohabereg commented on src/pages/game/Game.tsx
> +  const ctxRef = React.useRef<CanvasRenderingContext2D | null>(null);
Одновременно используешь `useRef` и `React.useRef`, стоит выбрать один вариант. Обычно хуки используют без React — то есть просто `useRef`

2022-04-28 20:55 UTC, gohabereg commented on src/pages/game/Game.tsx
> +      if (ctxRef.current) {
Не хватает пустых строк между выражениями
```suggestion
      const deltaTime = timestamp - lastTimeRef.current;

      lastTimeRef.current = timestamp;

      if (ctxRef.current) {
```

Стоит наверное отдельно настроить на это линтер

2022-04-28 20:55 UTC, gohabereg commented on src/pages/game/Game.tsx
> +        game.draw(ctxRef.current);
Сейчас получается, что каждый фрейм вызывается game.start — это не очень логично. Кажется, start должен вызываться только один раз

2022-04-28 20:55 UTC, gohabereg commented on src/pages/game/game.types.ts
> +export interface IPaddle {
Если у тебя есть класс, то для него не нужно отдельно использовать интерфейс. Класс можно использовать как тип

```
const paddle: Paddle = new Paddle();
```

Аналогично с IGame и IBall

2022-04-28 20:55 UTC, gohabereg commented on src/pages/game/game.types.ts
> +export interface IPaddle {
Напомни, пожалуйста, на синке, чтобы я подробнее об этом рассказал

2022-04-28 20:55 UTC, gohabereg commented on src/pages/game/utils/ball.ts
> +  readonly image: HTMLImageElement;
Очень не хватает пустых строк — очень сложно читать код

2022-04-28 20:55 UTC, gohabereg commented on src/pages/game/utils/ball.ts
> +    ballImage.src = ballImg;
Создание картинки можно вынести в отдельный приватный метод, а в конструкторе просто вызывать
```
this.image = this.createImage();
```

2022-04-28 20:55 UTC, gohabereg commented on src/pages/game/utils/ball.ts
> +    this.gameHeight = game.gameHeight;
Можно немножко улучшить читаемость, если использовать деструктор в параметре конструктора:
```
constructor({ gameWidth, gameHeight }: IGame) {
  ...
}
```

2022-04-28 20:55 UTC, gohabereg commented on src/pages/game/utils/ball.ts
> +    this.size = 16;
Эти значения можно указать сразу при объявлении свойства

```
public position: Position = {
  x: 10,
  y: 10,
};

public speed: Position = {
  x: 10,
  y: 10,
};

public readonly size = 10;
```

2022-04-28 20:55 UTC, gohabereg commented on src/pages/game/utils/ball.ts
> +  speed: Position;
Кстати, обычно структуру с x и y называют Vector2 (потому что например тут speed имеет тип Position, что не очень логично). Но это FYI, не обязательно менять

2022-04-28 20:55 UTC, gohabereg commented on src/pages/game/utils/ball.ts
> +  update(deltaTime?: number) {
deltaTime нигде не используется в методе, так и задумано?

2022-04-28 20:55 UTC, gohabereg commented on src/pages/game/utils/input.ts
> +  constructor(paddle: IPaddle) {
Есть мысль сделать `InputHandler` более абстрактным — отвязать от paddle. Например, чтобы он эмитил какое-то событие, на которое уже paddle и другие объекты могут подписаться. Но это не на сейчас, на потом

2022-04-28 20:55 UTC, gohabereg commented on src/pages/game/utils/paddle.ts
> +    this.speed = 0;
Тут аналогичные комменты к тому, что писал для Ball

2022-04-30 09:14 UTC, parnasmi commented on public/index.html
> +<!--<img src="ball.png" id="ballImage" alt="">-->
Забыл удалить. Убрал.

2022-04-30 09:14 UTC, parnasmi commented on src/pages/game/Game.tsx
> +  const ctxRef = React.useRef<CanvasRenderingContext2D | null>(null);
Исправил.

2022-04-30 09:34 UTC, parnasmi commented on src/pages/game/Game.tsx
> +      if (ctxRef.current) {
Спасибо. Настроил.

2022-04-30 09:39 UTC, parnasmi commented on src/pages/game/Game.tsx
> +        game.draw(ctxRef.current);
Переместил в useEffect

2022-04-30 09:47 UTC, parnasmi commented on src/pages/game/utils/ball.ts
> +  readonly image: HTMLImageElement;
Можно поподробнее?  Где нужно добавить пустых строк?

2022-04-30 09:48 UTC, parnasmi commented on src/pages/game/utils/ball.ts
> +    ballImage.src = ballImg;
Сделал.

2022-04-30 09:49 UTC, parnasmi commented on src/pages/game/utils/ball.ts
> +    this.gameHeight = game.gameHeight;
Спасибо. Деструктурировал.

2022-04-30 09:52 UTC, parnasmi commented on src/pages/game/utils/ball.ts
> +    this.size = 16;
Переделал.

2022-04-30 09:52 UTC, parnasmi commented on src/pages/game/utils/ball.ts
> +  update(deltaTime?: number) {
В начале использовал. Но, потом не было необхотимости.

2022-04-30 09:56 UTC, parnasmi commented on src/pages/game/utils/paddle.ts
> +    this.speed = 0;
Переделал. Спасибо.

2022-05-01 14:04 UTC, gohabereg requested changes
Есть еще мысли как улучшить код, но это можно будет позже сделать

Можно будет смерджить, после двух вещей:
1. Добавить все таки пустых строк между объявлением свойств классов/интерфейсов — в остальном коде теперь хорошо, спасибо
2. Удали пожалуйста все интерфейсы, которые дублируют классы. Везде, где они используются в качестве типов стоит просто использовать класс
Например
```
paddle: Paddle 
```

вместо

```
paddle: IPaddle
```

2022-05-01 14:04 UTC, gohabereg commented on src/pages/game/utils/game.ts
> +interface IGame {
Стоит переименовать во что-нибудь вроде `GameOptions`, чтобы не путать Game и IGame

2022-05-01 14:04 UTC, gohabereg commented on src/pages/game/utils/game.ts
> +interface IGame {
Тем более получается, что IGame объявлен два раза: тут и в `game.types`

2022-05-02 16:58 UTC, merged