Feature/brick breaker 7
13-Troy/brick-breaker pull request #26
Opened 2022-04-28 09:08 UTC by AFL987

2022-04-28 14:46 UTC, KaterinaKorneeeva commented on src/pages/profile/Profile.tsx
> +    fetch(`https://ya-praktikum.tech/api/v2/auth/logout`, {
лучше собрать все   урлы в одном месте

2022-04-28 14:46 UTC, KaterinaKorneeeva commented on src/components/DataLine/style.tsx
> +  color: #ffffff;
кстати,  весь список цветов есть в variables
import { allColors } from '../../styles/variables';

 color: ${allColors.white};

2022-04-28 14:46 UTC, KaterinaKorneeeva commented on src/layouts/Page.tsx
> +
видела такой вариант 

const initialState = {
    id: 0,
    email: '',
    first_name: '',
    second_name: '',
    display_name: '',
    phone: '',
    login: '',
    avatar: '',
}

const [user, setUser] = useState(initialState);

вроде как initialState потом можно использовать для сброса например формы

2022-04-28 20:33 UTC, gohabereg requested changes

2022-04-28 20:33 UTC, gohabereg commented on src/components/Avatar/Avatar.tsx
> +export default Avatar;
1. Опять дублируется интерфейс пропсов для компонента и styled компонента
2. И компонент тоже лишняя обертка тут

Можно все заменить на просто
```suggestion
export default AvatarSt;
```

2022-04-28 20:33 UTC, gohabereg commented on src/components/DataLine/style.tsx
> +  color: #ffffff;
А еще лучше через тему)
```
color: ${({theme}) => theme.white};
```
Цвет правда не знаю как у вас называется в теме


Важно использовать тему, потому что в одном из следующих спринтов будет требования реализовать альтернативную тему

2022-04-28 20:33 UTC, gohabereg commented on src/layouts/Page.tsx
> +          )}
Сейчас сойдет, но стоит тоже оставить todo чтобы потом реализовать guarded роуты

2022-04-28 20:33 UTC, gohabereg commented on src/pages/registration/Registration.tsx
> +      <form onSubmit={onSubmit}>
Тут бы я на самом деле тоже форму убрал. Это конечно семантически верно, но для SPA приложения не имеет никакого смысла — только усложняет логику и верстку

2022-04-29 07:24 UTC, AFL987 commented on src/components/Avatar/Avatar.tsx
> +export default Avatar;
ок

2022-04-29 07:24 UTC, AFL987 commented on src/components/DataLine/style.tsx
> +  color: #ffffff;
ок

2022-04-29 07:24 UTC, AFL987 commented on src/layouts/Page.tsx
> +
ок

2022-04-29 07:24 UTC, AFL987 commented on src/layouts/Page.tsx
> +          )}
ок

2022-04-29 07:24 UTC, AFL987 commented on src/pages/profile/Profile.tsx
> +    fetch(`https://ya-praktikum.tech/api/v2/auth/logout`, {
ок

2022-04-29 07:24 UTC, AFL987 commented on src/pages/registration/Registration.tsx
> +      <form onSubmit={onSubmit}>
ок

2022-04-29 07:24 UTC, AFL987 commented on src/layouts/Page.tsx
> +          )}
ок

2022-04-29 07:24 UTC, merged