Feature/brick breaker 12
13-Troy/brick-breaker pull request #27
Opened 2022-05-01 11:10 UTC by AFL987

2022-05-01 14:20 UTC, gohabereg requested changes

2022-05-01 14:20 UTC, gohabereg commented on src/pages/profile/Profile.tsx
> +        <Modal isShown={isShown} hide={toggleVisible}>
Компонент получился очень уж большим, такие сложно читать и поддерживать в будущем.

Предлагаю сделать такую штуку:
1. Получается, что всего тут три модальных окна: `changeAvatar`, `changeData` и `changePassword`
2. Значит нужно создать три компонента: `ChangeAvatarModal`, `ChangeProfileDataModal` и `ChangePasswordModal`

Каждый компонент будет выглядеть примерно так:

```
interface ChangeAvatarModalProps {
  onClose: (newAvatar: File) => void // для других двух соответственно будет newData/newPassword
  // для ChangeProfileData скорее всего надо будет еще передать текущие значения
}

const ChangeAvatarModal: FC<ChangeAvatarModalProps> = ({ onClose }) => {
  const [newAvatar, setAvatar] = useState<File | undefined>();
  const [isShown, toggleVisible] = useToggle(false);

  const onChange = (e) => {
    setAvatar(e.target.files[0]); // тут чтобы не было ошибки, нужно задать правильный тип для e
  }

  return (
    <Modal isShown={isShown} hide={toggleVisible}>
      <Title h={4}>{'загрузите файл'}</Title>
            <Input
              name={'avatar'}
              type={'file'}
              placeholder={'file'}
              onChange={onChange}
            />
            <Button fullWidth onClick={onClose}>
              поменять
            </Button>
   </Modal>
  )
}
```

То есть логика переезжает в сами компоненты

3. А в этом компоненте уже соответственно подключить три компонента по одной строке

2022-05-01 14:20 UTC, gohabereg commented on src/pages/500/ServerError.tsx
> +  return (
Обе страницы ошибки выглядят одинаково и дублируют код, поэтому предлагаю вынести общий код в компонент `ErrorPageTemplate`

```
interface ErrorPageTemplateProps {
  title: string;
  subtitle: string;
}

const ErrorPageTemplate = FC<ErrorPageTemplateProps> = ({ title, subtitle }) => {
  const navigate = useNavigate();

  const goBack = () => navigate(-1);

  return (
    <CenterSt>
      <div> // для этого div лучше завести отдельный st компонент, а не стилизовать его внутри CenterSt
        <BigSt>{title}</BigSt>
        <SmallSt>{subtitl}</SmallSt>
      </div>
      <Button fullWidth={false} onClick={goBack}>
        назад
      </Button>
    </CenterSt>
  )
}
```

А сами страницы будут выглядеть так

```
const ServerError: FC = () => {
  return <ErrorPageTemplate title="500" subtitle="упс, ошибка сервера" />
}

const NotFoundError: FC = () => {
  return <ErrorPageTemplate title="404" subtitle="упс, страница не найдена" />
}
```

2022-05-01 16:12 UTC, AFL987 commented on src/pages/profile/Profile.tsx
> +        <Modal isShown={isShown} hide={toggleVisible}>
Разделил

2022-05-01 16:13 UTC, AFL987 commented on src/pages/500/ServerError.tsx
> +  return (
Вынес

2022-05-02 19:39 UTC, gohabereg approved these changes

2022-05-02 19:39 UTC, merged