Feature/brick breaker 15
13-Troy/brick-breaker pull request #28
Opened 2022-05-04 20:14 UTC by KaterinaKorneeeva

пытаюсь сделать универсальный компонент таблица

```
export const forumList = [
  {
    id: 1,
    name: 'Правила форума',
    user_id: 32,
    user_name: 'Семен',
    answer_count: 55,
    content: 'this is text content',
  },
  ... }]
```
есть такой массив с темами , в таблице не хочу отображать поле content и user_id
исключаю эти поля 
forumList.map((forum) => delete forum.content);
 forumList.map((forum) => delete forum.user_id); 
 
  и отправляю в таблицу
  
  а в самой таблице еще убираю поле id, тк это для всех таблиц подходит (не показывать id)
  
  ```
 {Object.keys(obj)
              .filter((key) => key !== 'id')
              .map((key, index) => (
                <TableColSt key={index}>{obj[key]}</TableColSt>
              ))}
```

typescript выдает ошибки 
```
ERROR in /Users/ekorneeva/Desktop/yandex/brick-breaker/src/pages/forum/Forum.tsx(15,35)
     TS2790: The operand of a 'delete' operator must be optional.
      
TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{}'.
  No index signature with a parameter of type 'string' was found on type '{}'.

[tsl] ERROR in /Users/ekorneeva/Desktop/yandex/brick-breaker/src/components/Table/Table.tsx(41,61)
  TS2339: Property 'id' does not exist on type 'object'.
```
  
  Подскажи пож как это сделать правильно)

2022-05-05 19:49 UTC, gohabereg requested changes
Поправь еще пожалуйста варнинги от ESLint

2022-05-05 19:49 UTC, gohabereg commented on src/components/Table/Table.tsx
> +  colNames: Array<string>;
Обычно рекомендуют нотацию `string[]` вместо `Array<string>` — так получается короче

```suggestion
  colNames: string[];
```

2022-05-05 19:49 UTC, gohabereg commented on src/components/Table/Table.tsx
> +  content: Array<object>;
Чтобы ошибки ушли, вот тут нужно тип указать `Array<Record<string, string>>` или `Record<string, string>[]` что одно и то же.

Тип `object` вообще рекомендую не использовать, от него больше проблем, чем пользы

2022-05-05 19:49 UTC, gohabereg commented on src/components/Table/Table.tsx
> +  );
Можно смело вынести в отдельный компонент, так его и назвать `TableHead`

2022-05-05 19:49 UTC, gohabereg commented on src/components/Table/Table.tsx
> +              ))}
Вот это лучше или вынести в переменную, или в отдельный компонент. Чтобы не нагружало разметку

2022-05-05 19:49 UTC, gohabereg commented on src/pages/forum/Forum.tsx
> +  const filterForumData = (post: any) => {
Стоит добавить интерфейс `Post` и типизировать переменную `post`

2022-05-05 19:49 UTC, gohabereg commented on src/pages/forum/Forum.tsx
> +      }, {});
Если я правильно понял, то все это можно заменить на
```
delete post.content;
delete post.user_id;
```

2022-05-05 19:49 UTC, gohabereg commented on src/pages/forum/Forum.tsx
> +  const adaptPosts = forumList.map((post: object) => filterForumData(post));
Можно упростить
```suggestion
  const adaptPosts = forumList.map(filterForumData);
```

2022-05-05 19:49 UTC, gohabereg commented on src/pages/forum/Forum.tsx
> +  const [logIn, setLogIn] = useState({ name: '', content: '' });
Старайтесь использование хуков, особенно useState, переносить в начало компонента — так сразу понятно, какое у него есть состояние, рефы и тд

2022-05-05 19:49 UTC, gohabereg commented on src/pages/forum/Forum.tsx
> +  const adaptPosts = forumList.map((post: object) => filterForumData(post));
А еще эту переменную кажется можно вынести за компонент, чтобы она тут не мешалась)

2022-05-05 19:49 UTC, gohabereg commented on src/pages/forum/Forum.tsx
> +        </Modal>
Рекомендую создать отдельный компонент `EditProfileModal`, в который вынести эту часть. В нем же можно и состояние хранить

2022-05-05 19:49 UTC, gohabereg commented on src/pages/post/Post.tsx
> +    <>
Фрагмент тут лишний, можно убрать

2022-05-07 19:43 UTC, KaterinaKorneeeva commented on src/pages/forum/Forum.tsx
> +  const handleAdd = useCallback(() => {
добавила useCallback и eslint ругается
`49:6  warning  React Hook useCallback has a missing dependency: 'toggleVisible'. Either include it or remove the dependency array  react-hooks/exhaustive-deps`

2022-05-08 17:23 UTC, gohabereg approved these changes

2022-05-08 17:23 UTC, gohabereg commented on src/components/CreatePostModal/CreatePostModal.tsx
> +  handleChange,
Не обязательно, но можно хранить состояние инпутов внутри этого компонента, а результат отдавать родителю через `handleAdd` при нажатии на сохранить, тогда этот компонент можно будет переиспользовать в любом месте — не придется реализовывать состояние в родителе

2022-05-08 17:23 UTC, gohabereg commented on src/pages/forum/Forum.tsx
> +  const handleAdd = useCallback(() => {
useCallback мемоизирует функцию, а зависимости указывают на переменные, при изменении которых нужно обновить закэшированную функцию. Так как ты внутри используешь `useVisible`, то линтер говорит, что нужно добавить это как зависимость

2022-05-08 17:23 UTC, gohabereg commented on src/pages/forum/style.tsx
> +  background: #fff;
Можно вынести в тему

2022-05-11 10:19 UTC, AFL987 approved these changes

2022-05-15 13:20 UTC, merged