Feature/redux test
13-Troy/brick-breaker pull request #29
Opened 2022-05-09 14:26 UTC by AFL987

2022-05-09 16:54 UTC, gohabereg requested changes

2022-05-09 16:54 UTC, gohabereg commented on src/store/user/actions.ts
> +export const changeDataAction = (newData: any) => {
Обычно thunk именуют от действия — `changeUserData`
Еще лучше, если действие называется по юз-кейсу —  `updateProfileData`

2022-05-09 16:54 UTC, gohabereg commented on src/store/user/actions.ts
> +export const userAction = () => {
От действия — `getProfile` / `getProfileData`

2022-05-09 16:54 UTC, gohabereg commented on src/store/user/actions.ts
> +    fetch(`${UrlSite.URL}/auth/user`, {
Рекомендую завести отдельный класс для HTTP запросов

2022-05-09 16:54 UTC, gohabereg commented on src/store/user/actions.ts
> +    fetch(`${UrlSite.URL}/auth/user`, {
Рекомендую использовать async/await

2022-05-09 16:54 UTC, gohabereg commented on src/store/user/reducer.ts
> +  user: {
Лишняя вложенность, можно передать сразу объект `user`

2022-05-16 05:27 UTC, AFL987 commented on src/store/user/actions.ts
> +export const changeDataAction = (newData: any) => {
ok

2022-05-16 05:27 UTC, AFL987 commented on src/store/user/actions.ts
> +export const userAction = () => {
ok

2022-05-16 05:27 UTC, AFL987 commented on src/store/user/reducer.ts
> +  user: {
ok

2022-05-16 05:35 UTC, AFL987 commented on src/store/user/actions.ts
> +    fetch(`${UrlSite.URL}/auth/user`, {
Без крайней необходимости не хотелось бы(

2022-05-16 15:58 UTC, gohabereg requested changes

2022-05-16 15:58 UTC, gohabereg commented on src/components/ChangeProfileDataModal/ChangeProfileDataModal.tsx
> +    updateProfileData(data)(dispatch);
Thunks используются не совсем так
```suggestion
    dispatch(updateProfileData(data));
```

2022-05-16 15:58 UTC, gohabereg commented on src/store/user/actions.ts
> +    fetch(`${UrlSite.URL}/auth/user`, {
Не совсем понял, к какому это комменту?

2022-05-16 17:56 UTC, gohabereg approved these changes

2022-05-16 18:14 UTC, KaterinaKorneeeva approved these changes

2022-05-16 18:23 UTC, parnasmi approved these changes

2022-05-16 18:24 UTC, merged