Refactor/game mechanics
13-Troy/brick-breaker pull request #36
Opened 2022-05-09 16:55 UTC by parnasmi

2022-05-14 14:23 UTC, gohabereg requested changes

2022-05-14 14:23 UTC, gohabereg commented on src/pages/game/utils/InputManager.ts
> +    this.game.emit(event);
Тут точно нужно через `game` это делать?
Кажется, будет правильнее вызывать просто `this.emit(event)`, чтобы подписчики напрямую подписывались на InputManager, а не на Game

2022-05-14 14:23 UTC, gohabereg commented on src/pages/game/utils/ball.ts
> +    this.emit('updated', this);
Можно стены тоже сделать игровыми объектами, которые просто не будут отрисовываться. Тогда не придется отдельно тут обрабатывать столкновение, а просто добавить в CollisionManager

```
colllisionManager.watch(ball, leftWall);
colllisionManager.watch(ball, rightWall);
colllisionManager.watch(ball, topWall);
colllisionManager.watch(ball, bottomWall);
```

Ну и подписываться тут на события столкновения со стенами

2022-05-14 14:23 UTC, gohabereg commented on src/pages/game/utils/game.ts
> +
Лучше все таки, чтобы эти события эммитили соответствующие объекты — InputManager и ball в данном случае

2022-05-14 14:23 UTC, gohabereg commented on src/pages/game/utils/input.ts
> +export class InputHandler extends EventEmitter {
Кажется нужно или избавиться от этого класса и перенести весь функционал внутрь InputManager, или сделать обратную композицию — сейчас inputManager передается сюда из-вне, кажется что должно быть наоборот — InputHandler должен создаваться внутри InputManager

2022-05-15 03:40 UTC, parnasmi commented
Спасибо за правки. Завтра возьмусь за исправлении.

2022-05-16 15:29 UTC, parnasmi commented on src/pages/game/utils/InputManager.ts
> +    this.game.emit(event);
Ок. Спасибо. Отрефакторю тогда.

2022-05-16 17:01 UTC, AFL987 approved these changes

2022-05-19 08:35 UTC, gohabereg approved these changes

2022-05-19 08:49 UTC, merged