Feature/brick breaker 3
13-Troy/brick-breaker pull request #4
Opened 2022-04-21 10:00 UTC by AFL987

2022-04-21 14:55 UTC, KaterinaKorneeeva commented on .babelrc
> +}
Для git важно наличие [пустой строки](https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log) в конце файла.

2022-04-21 14:55 UTC, KaterinaKorneeeva commented on src/components/NavTest/NavTest.tsx
> +      <Link to={'/'}>home</Link><br/>
предлагаю сразу вынести ссылки в файл const.js для удобного использования в др файлах (например когда понадобиться  использовать redirect)

export const AppRoute = {
  ROOT: `/`,
  ABOUT: `/about`,
  REGISTRATION: `/registration`,
  PROFILE: `/profile`,
  FORUM: `/forum`,
  RECORDS: `/records`,
  GAME: `/game`,
};

2022-04-22 13:45 UTC, gohabereg requested changes

2022-04-22 13:45 UTC, gohabereg commented on .babelrc
> +}
Предлагаю для настройки этого использовать файл .editorconfig — https://editorconfig.org/

2022-04-22 13:45 UTC, gohabereg commented on package.json
> +    "@types/react-dom": "18.0.1",
Пакеты с типами стоит перенести в devDependencies, так как в сборке они не участвуют

2022-04-22 13:45 UTC, gohabereg commented on src/styles/style.scss
> +* {
Так как вы решили использовать StyledComponents, вместо css файла лучше использовать функцию `createGlobalStyle`
https://styled-components.com/docs/api#createglobalstyle

2022-04-22 13:45 UTC, gohabereg commented on www/index.html
> +<!DOCTYPE html>
Обычно ассеты кладут в папку public или assets, `www` вариант давно уже не видел)

Это не к тому, что нужно это менять, скорее просто FYI

2022-04-22 14:09 UTC, AFL987 commented on www/index.html
> +<!DOCTYPE html>
Я, честно говоря, тоже давно не видел, но вот у вас в учебнике рекомендуют почему-то :)

![Снимок экрана от 2022-04-22 17-06-04](https://user-images.githubusercontent.com/99122951/164731077-f3b6af20-c6e0-4fe1-be4f-9b841a0dcec2.png)
![Снимок экрана от 2022-04-22 17-06-59](https://user-images.githubusercontent.com/99122951/164731081-ca2fac34-48bd-497d-8c49-d7985d045ee9.png)

2022-04-25 11:41 UTC, gohabereg approved these changes
Вижу, что пропал babel. Пока думаю можно действительно без него, но потом надо будет глянуть в разных браузерах как будет работать

2022-04-25 16:04 UTC, merged