Feature/oath
13-Troy/brick-breaker pull request #51
Opened 2022-05-28 13:18 UTC by parnasmi

2022-05-29 23:39 UTC, gohabereg requested changes

2022-05-29 23:39 UTC, gohabereg commented on src/hooks/useOauth.ts
> +      document.location.href = getOauthCodeRedirect(
Думаю, стоит это открывать в новом окне

2022-05-29 23:39 UTC, gohabereg commented on src/pages/home/Home.tsx
> +  const redirect_uri = window.location.origin;
Обычно для OAuth используют отдельный урл, например `/oauth` или `/oauth-callback`, чтобы точно знать, что на нем нужно обрабатывать авторизацию

2022-06-08 14:08 UTC, gohabereg approved these changes

2022-06-08 14:08 UTC, gohabereg commented on src/pages/oauth/Oauth.tsx
> +    <ErrorPageTemplate
Не очень логично получается, что используется ErrorPageTemplate, хотя тут нет ошибки. Можно переименовать компонент

2022-06-08 14:08 UTC, gohabereg commented on src/services/HTTPTransport/HTTPTransport.ts
> +      return response as unknown as Promise<T>;
Тут можно возвращать response.text()

2022-06-14 16:21 UTC, AFL987 approved these changes

2022-06-15 10:33 UTC, KaterinaKorneeeva approved these changes

2022-06-16 03:46 UTC, merged